input_data_path: "data/processed/heart_cleveland_upload.csv"
output_model_path: "models/"
metric_path: "reports/metrics/"
train_x_path: "data/processed/train_x.csv"
test_x_path: "data/processed/test_x.csv"
train_y_path: "data/processed/train_y.csv"
test_y_path: "data/processed/test_y.csv"

# downloading_params:
#   s3_bucket: for-dvc
#   paths:
#     - train.csv
#     - test.csv
#   output_folder: "data/processed/"

splitting_params:
  val_size: 0.2
  random_state: 3

train_params:
  model_type: "LogisticRegression"
  random_state: 3


use_mlflow: False

feature_params:
  categorical_features:
    - "sex"
    - "chest pain"
    - "fasting blood sugar"
    - "resting electrocardiographic results"
    - "exercise induced angina"
    - "slope"
    - "number of major vessels"
    - "thal"
  numerical_features:
    - "age"
    - "resting blood pressure"
    - "cholesterol"
    - "max heart rate"
    - "oldpeak"
  target_col: "condition"
  use_log_trick: False

# transform_params:
#   ohe_categorical: True
#   normalize_numerical: True